### ISSUE TITLE
major, minorが2桁だとクラッシュする

### ISSUE THREAD

**Issue by hyouhyan** [nanocom2024/nanoRelation_Device#9]
major: 10、minor: 20のときにクラッシュを確認
1桁(1,2)でもクラッシュを確認
3桁(100, 200)や4桁(1000,2000)では確認できず

おそらく、~~パースがうまく行っていないと思われる~~
major, minorを認識して**発信は**できるので、パースは問題なさそう。
iBeaconモードへの切り替えの際、アドバタイズデータの上書きに失敗してるのかも。

**Comment by k22036** [comment]
正しく分割されているけど，クラッシュする感じ？

**Comment by hyouhyan** [comment]
@k22036 
> 正しく分割されているけど，クラッシュする感じ？

うん。分割は問題なかった。

正確に言うと、1桁でも2桁でもiBeaconの発信は問題なく出来る。
ただ、BLEモジュールを寝かせようとするところでフリーズしちゃう感じ。
荒治療だけど、寝かせず常時発信すれば問題はない。

**Comment by hyouhyan** [comment]
なんか治った…何もしてないのに…

もしかして、 47b6205c4029851b04a430358ae23e8a13638ccc の影響？

**Comment by hyouhyan** [comment]
`git revert 47b6205c4029851b04a430358ae23e8a13638ccc`したら問題が再発したので、 47b6205c4029851b04a430358ae23e8a13638ccc の影響で治ったのは確定。
lost関連のパースが暴発してmajorとminorを上書きしちゃったのかな？
